<?php
/**
 * Created by PhpStorm.
 * User: lfaus
 * Date: 2019-03-07
 * Time: 18:28
 */

class DofaCommentSbumitModuleFrontController extends ModuleFrontController
{
     public function postProcess()
    {
        parent::postProcess(); // TODO: Change the autogenerated stub\
/**

        if ($_SERVER["REQUEST_METHOD"] == "POST")
            {
                $username = test_input($_POST["username"]);
                $email = test_input($_POST["email"]);
                $phone_number = test_input($_POST["phone_number"]);
                $comment = test_input($_POST["comment"]);

             }

        function test_input($data)
            {
                $data = trim($data);
                $data = stripslashes($data);
                $data = htmlspecialchars($data);
                return $data;
            }
        var_dump($_POST);
        die();
        $sql = "INSERT INTO ps_product_comments () VALUES ('$username',  )";
  */
    }


}